import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ms Home",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="flex justify-center align-middle  bg-orange-700 rounded">
          <Link
            className="text-[30px] font-bold p-2 m-2 bg-orange-800 hover:bg-orange-600 transition-all rounded-[20px]"
            href={"/"}
          >
            Home
          </Link>
          <Link
            className="text-[30px] font-bold p-2 m-2 bg-orange-800 hover:bg-orange-600 transition-all rounded-[20px]"
            href={"/useclient"}
          >
            Api by 'UseClient'
          </Link>
          <Link
            className="text-[30px] font-bold p-2 m-2 bg-orange-800 hover:bg-orange-600 transition-all rounded-[20px]"
            href={"/about"}
          >
            about
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
